#!/usr/bin/python

# ask
# 11-411 NLP Spring 2013, Group 6
# (Stub) Authored by Ryhan Hassan | rhassan@andrew.cmu.edu

# Useful tools which should be pre-installed
import os, sys, errno
import re
import itertools
import nltk

# Import our modules from /modules
sys.path.append("modules")
import questionContentSelector

# Returns string containing content at file path.
def read_file(path):
  content = ""
  content = open(path).read()
  return content

if __name__ == '__main__':
  path_to_article = sys.argv[1]
  num_questions = int(sys.argv[2])
  print("Generating " + str(num_questions) + " questions:")

  # Pre-process article content.
  article_content = open(path_to_article).read()

  # Should probably apply co-reference resolution to article content here.

  # Decide how many candidates we want to generate
  num_cand = num_questions*10

  # Fetch sentence candidates that can be converted into questions.
  selected_content = questionContentSelector.process(article_content, num_cand)

  # Use POS Tagging and Transformation rules to generate questions
  # Below is a temporary, incredibly naive question generator.
  questions = [ ]
  for sentence in selected_content:
    if ("It is" in sentence) and (sentence[len(sentence) -1] == "."):
      question = sentence[:len(sentence)-1] + str("?")
      question = sentence.replace("It is", "What is")
      questions.append(question)

  # Rank generated questions and return top [:num_questions]

  questions = questions[:num_questions]
  for question in questions:
    print(question)
